# Generated by Django 5.1.2 on 2024-10-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Biography', 'Biography'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('War', 'War'), ('Gangster', 'Gangster'), ('Horror', 'Horror')], max_length=50),
        ),
    ]
